const studentProfileInput = document.getElementById("studentProfile");
const opportunitiesInput = document.getElementById("opportunities");
const resultCards = document.getElementById("resultCards");
const resultStatus = document.getElementById("resultStatus");
const inputHint = document.getElementById("inputHint");
const analyzeButton = document.getElementById("analyzeButton");
const analyzeCatalogButton = document.getElementById("analyzeCatalogButton");
const loadSampleButton = document.getElementById("loadSampleButton");
const loadCatalogButton = document.getElementById("loadCatalogButton");
const catalogGrid = document.getElementById("catalogGrid");

const catalogOpportunities = [
  {
    name: "Summer Science Research Program (SSRP)",
    organization: "Rockefeller University",
    type: "program",
    location: "New York, NY",
    duration: "Jun 24 - Aug 8",
    deadline: "Jan 4, 2027",
    difficulty: "very hard",
    eligibility: "High school juniors and seniors interested in scientific careers; full-time summer commitment required.",
    tags: ["research", "science", "lab", "stem"],
    description: "A free seven-week research program where students work in small lab teams, learn research methods, and present a final poster.",
    link: "https://www.snow.day/learning-opportunities/622ff0be-8074-4560-b4a7-202abed1c9fe/summer-science-research-program-ssrp",
    competitiveness: "Highly competitive",
    requirements: "Strong interest in science, research commitment, full-time weekday availability",
    upside: "Free research experience, poster presentation, professional network"
  },
  {
    name: "MITES Summer",
    organization: "MIT",
    type: "program",
    location: "Cambridge, MA",
    duration: "Jun - Sep",
    deadline: "Feb 2, 2027",
    difficulty: "very hard",
    eligibility: "Rising high school seniors interested in STEM.",
    tags: ["stem", "engineering", "math", "college prep"],
    description: "A free residential STEM immersion with advanced coursework, electives, and college readiness support for rising seniors.",
    link: "https://www.snow.day/learning-opportunities/0cb45d42-14f6-40b4-92b3-41afce318d26/mites-summer",
    competitiveness: "Highly competitive",
    requirements: "Strong STEM interest, rising senior status, full summer academic commitment",
    upside: "Prestigious STEM program, advanced coursework, residential experience"
  },
  {
    name: "Broad Summer Scholars Program (BSSP)",
    organization: "Broad Institute",
    type: "program",
    location: "Cambridge, MA",
    duration: "Jun 30 - Aug 8",
    deadline: "Jan 22, 2027",
    difficulty: "very hard",
    eligibility: "Highly motivated high school students with strong interest in science.",
    tags: ["research", "biology", "science", "stem"],
    description: "A free six-week summer research program pairing students with Broad scientists for original projects and scientific presentations.",
    link: "https://www.snow.day/learning-opportunities/9bdfe6ec-ade5-4501-b125-3cc721fad01c/broad-summer-scholars-program-bssp",
    competitiveness: "Highly competitive",
    requirements: "Strong science interest, ability to contribute to research teams, motivation for intensive summer work",
    upside: "Mentored research, scientific talks, college fair exposure"
  },
  {
    name: "Princeton Summer Journalism Program (PSJP)",
    organization: "Princeton University",
    type: "program",
    location: "Princeton, NJ",
    duration: "Jul 27 - Aug 6",
    deadline: "Feb 25, 2027",
    difficulty: "hard",
    eligibility: "High-achieving high school juniors from low-income backgrounds interested in journalism.",
    tags: ["journalism", "writing", "media", "college prep"],
    description: "A journalism and college-prep program blending summer workshops, writing assignments, and an on-campus residential institute.",
    link: "https://www.snow.day/learning-opportunities/f2e8d330-39b9-4736-9c83-620f25f12a4b/princeton-summer-journalism-program-psjp",
    competitiveness: "Competitive",
    requirements: "High academic achievement, junior status, journalism interest, low-income eligibility",
    upside: "Selective journalism training, college counseling, campus experience"
  },
  {
    name: "Athena Summer Innovation Institute",
    organization: "Barnard College",
    type: "program",
    location: "New York, NY",
    duration: "Jun 30 - Jul 18",
    deadline: "Rolling",
    difficulty: "medium",
    eligibility: "High school students interested in entrepreneurship and social impact.",
    tags: ["business", "entrepreneurship", "leadership", "innovation"],
    description: "A three-week entrepreneurship program where students build venture ideas through workshops, mentorship, and team collaboration.",
    link: "https://www.snow.day/learning-opportunities/ec1d7b93-011e-48ff-a881-9b1d521ad2a5/athena-summer-innovation-institute",
    competitiveness: "Moderate",
    requirements: "Interest in innovation, teamwork, and entrepreneurial problem-solving",
    upside: "Mentorship, venture-building experience, leadership development"
  },
  {
    name: "Project SEED Program",
    organization: "American Chemical Society",
    type: "program",
    location: "Washington, DC",
    duration: "8 - 10 weeks",
    deadline: "May 1",
    difficulty: "hard",
    eligibility: "High school students from diverse identities and socioeconomic backgrounds interested in chemistry research.",
    tags: ["chemistry", "research", "science", "college readiness"],
    description: "A summer research and college-readiness program connecting students with chemistry-focused mentors in academia and industry.",
    link: "https://www.snow.day/learning-opportunities/a3c2e64f-5fd8-4783-9042-780da92a4e2d/project-seed-program",
    competitiveness: "Competitive",
    requirements: "Science interest, ability to participate in research, chemistry-related curiosity",
    upside: "Mentored research, virtual camp, professional development"
  },
  {
    name: "Summer Law Institute",
    organization: "Legal Outreach",
    type: "program",
    location: "New York City, NY",
    duration: "5 weeks",
    deadline: null,
    difficulty: "medium",
    eligibility: "Rising ninth graders interested in law and professional skills development.",
    tags: ["law", "public speaking", "leadership", "career exposure"],
    description: "A five-week law-focused summer experience where students learn legal topics, meet attorneys, and take part in a mock trial.",
    link: "https://www.snow.day/learning-opportunities/89e0fffe-6425-49d3-9481-b721261b5eef/summer-law-institute",
    competitiveness: "Moderate",
    requirements: "Rising ninth grade status and interest in law, professional exposure, and mock trial work",
    upside: "Legal career exposure, mentor access, pathway to later program participation"
  },
  {
    name: "Stanford Institutes of Medicine Summer Research Program",
    organization: "Stanford University",
    type: "program",
    location: "Stanford, CA",
    duration: "Jun 9 - Jul 31",
    deadline: "Feb 22, 2027",
    difficulty: "very hard",
    eligibility: "U.S. juniors or seniors age 16+ with strong interest in medicine or biological sciences.",
    tags: ["medicine", "research", "biology", "stem"],
    description: "An eight-week biomedical research program where students work with Stanford mentors on medically oriented projects.",
    link: "https://www.snow.day/learning-opportunities/c5f0bcae-77ba-4f1f-b068-44e11ef5a7c6/stanford-institute-of-medicine-summer-research-program",
    competitiveness: "Highly Selective",
    requirements: "Junior or senior standing, age 16+, U.S. citizenship or permanent residency",
    upside: "Top-tier medical research exposure, mentored project work, strong resume impact"
  },
  {
    name: "Global Sports and Entertainment Business Summer Program",
    organization: "Loyola Marymount University (LMU)",
    type: "program",
    location: "Los Angeles, CA",
    duration: "2 weeks",
    deadline: null,
    difficulty: "medium",
    eligibility: "Rising high school sophomores, juniors, and seniors interested in sports and entertainment business.",
    tags: ["business", "sports", "media", "leadership"],
    description: "A residential business program exploring sports and entertainment careers through workshops, team projects, and industry-facing learning.",
    link: "https://www.snow.day/learning-opportunities/dda32a82-5f2c-448f-bd85-2cde05690627/global-sports-and-entertainment-business-summer-program",
    competitiveness: "Moderate",
    requirements: "Interest in business, media, sports, or entertainment with willingness to collaborate in teams",
    upside: "Career exposure, leadership development, residential business experience"
  },
  {
    name: "Boston University Summer Theatre Institute",
    organization: "Boston University College of Fine Arts",
    type: "program",
    location: "Boston, MA",
    duration: "Jun 30 - Jul 27",
    deadline: "Rolling",
    difficulty: "medium",
    eligibility: "High school students interested in theatre and performing arts.",
    tags: ["arts", "theatre", "performance", "creative"],
    description: "A four-week intensive summer program where students develop acting, voice, and stagecraft skills through hands-on workshops and production work.",
    link: null,
    competitiveness: "Moderate",
    requirements: "Interest in theatre, willingness to participate in group work and performances",
    upside: "Hands-on theatre experience, portfolio building, college-level instruction"
  },
  {
    name: "Deepen 1:1 Work Experience",
    organization: "Delta Institute",
    type: "internship",
    location: "Online",
    duration: "Year Round (Rolling)",
    deadline: "Rolling",
    difficulty: "easy",
    eligibility: "High school students interested in research, leadership, and mentorship.",
    tags: ["research", "leadership", "mentoring", "online"],
    description: "A flexible one-on-one mentorship program pairing students with professionals for guided research projects and leadership development.",
    link: null,
    competitiveness: "Open enrollment",
    requirements: "Interest in self-directed learning, basic computer access",
    upside: "Flexible schedule, personalized mentorship, resume building"
  },
  {
    name: "Barrett Summer Scholars (BSS)",
    organization: "Arizona State University",
    type: "program",
    location: "Various (In Person)",
    duration: "Summer (Various)",
    deadline: "Rolling",
    difficulty: "medium",
    eligibility: "High school students exploring college-level academics and different subjects.",
    tags: ["college prep", "stem", "arts", "leadership"],
    description: "A multi-track summer experience offering hands-on exploration in STEM, business, arts, and more at Arizona State University campuses.",
    link: null,
    competitiveness: "Moderate",
    requirements: "Completed application, interest in exploring college subjects",
    upside: "College campus exposure, multiple subject tracks, academic exploration"
  },
  {
    name: "SEASCape: Ocean Studies On The Cape",
    organization: "Sea Education Association",
    type: "program",
    location: "Falmouth, MA",
    duration: "Summer (Various)",
    deadline: "Rolling",
    difficulty: "hard",
    eligibility: "High school students interested in marine science, oceanography, and environmental studies.",
    tags: ["science", "environment", "marine", "research"],
    description: "An immersive ocean studies program combining classroom learning with hands-on research aboard a historic sailing vessel.",
    link: null,
    competitiveness: "Competitive",
    requirements: "Interest in marine science, physical fitness for on-board work",
    upside: "Unique oceanic research experience, sailing certification, environmental fieldwork"
  },
  {
    name: "Talaria Summer Institute",
    organization: "Talaria",
    type: "program",
    location: "Online and In Person",
    duration: "Summer (Various)",
    deadline: "Rolling",
    difficulty: "easy",
    eligibility: "High school students seeking leadership and personal development opportunities.",
    tags: ["leadership", "innovation", "personal development", "career"],
    description: "A flexible summer institute offering workshops and projects in leadership, innovation skills, and career readiness.",
    link: null,
    competitiveness: "Open enrollment",
    requirements: "Open to all high school students, self-motivation",
    upside: "Flexible format, career skills, leadership certificate"
  },
  {
    name: "U.S. Department of Education Internships",
    organization: "United States Department of Education",
    type: "internship",
    location: "Washington, DC",
    duration: "Various",
    deadline: "Rolling",
    difficulty: "hard",
    eligibility: "High school and college students interested in education policy and public service.",
    tags: ["government", "policy", "education", "public service"],
    description: "Internship opportunities at the federal Department of Education working on education policy, research, and program administration.",
    link: null,
    competitiveness: "Competitive",
    requirements: "Interest in education policy, U.S. citizenship may be required",
    upside: "Federal government experience, policy exposure, public service credentials"
  },
  {
    name: "Agri-TREK/Sci-TREK",
    organization: "Tuskegee University",
    type: "program",
    location: "Tuskegee, AL",
    duration: "Jun 7 - Jun 20",
    deadline: "Rolling",
    difficulty: "medium",
    eligibility: "High school students interested in agriculture, science, and technology.",
    tags: ["stem", "agriculture", "science", "technology"],
    description: "A two-week residential program exploring the intersection of agriculture and science through hands-on experiments and field work at a historic university.",
    link: null,
    competitiveness: "Moderate",
    requirements: "Interest in agriculture or science, willingness to participate in field activities",
    upside: "Residential college experience, hands-on science, agricultural technology exposure"
  },
  {
    name: "Austin Public Library Teen Volunteer Program",
    organization: "Austin Public Library",
    type: "volunteer",
    location: "Austin, TX",
    duration: "Year Round",
    deadline: "Rolling",
    difficulty: "easy",
    eligibility: "Teenagers interested in community service and library programs.",
    tags: ["community", "volunteer", "service", "library"],
    description: "A flexible volunteer program where teens help with library events, tutoring, and community outreach activities.",
    link: null,
    competitiveness: "Open enrollment",
    requirements: "Teen age (13-18), interest in helping community",
    upside: "Community service hours, flexible scheduling, library experience"
  },
  {
    name: "Bossgirls Summer Program",
    organization: "Zahn Innovation Center",
    type: "program",
    location: "New York, NY",
    duration: "Jun 29 - Jul 30",
    deadline: "Rolling",
    difficulty: "medium",
    eligibility: "Young women and gender-diverse students interested in entrepreneurship and business.",
    tags: ["business", "entrepreneurship", "leadership", "women in stem"],
    description: "A month-long entrepreneurship program empowering young women to develop business ideas, build prototypes, and pitch to mentors.",
    link: null,
    competitiveness: "Moderate",
    requirements: "Identify as female or gender-diverse, interest in entrepreneurship",
    upside: "Women-focused mentorship, prototype building, pitch experience"
  },
  {
    name: "Camp Innovate and Investigate",
    organization: "The College of New Jersey",
    type: "program",
    location: "Ewing Township, NJ",
    duration: "Jul 20 - Jul 24",
    deadline: "Rolling",
    difficulty: "easy",
    eligibility: "Middle and high school students curious about STEM and innovation.",
    tags: ["stem", "innovation", "hands-on", "beginner"],
    description: "A week-long day camp offering hands-on STEM activities, experiments, and teamwork challenges at a local college campus.",
    link: null,
    competitiveness: "Open enrollment",
    requirements: "Curiosity about STEM, ability to attend daily sessions",
    upside: "Short commitment, fun hands-on projects, college campus exposure"
  },
  {
    name: "Chicago Summer Business Institute",
    organization: "Chicago Summer Business Institute",
    type: "program",
    location: "Chicago, IL",
    duration: "Jun - Jul (Summer)",
    deadline: "Rolling",
    difficulty: "medium",
    eligibility: "High school students interested in business, finance, and entrepreneurship.",
    tags: ["business", "finance", "entrepreneurship", "career"],
    description: "An intensive business program in Chicago featuring workshops, company visits, and mentorship from industry professionals.",
    link: null,
    competitiveness: "Moderate",
    requirements: "Interest in business careers, willingness to participate actively",
    upside: "Company visits, professional mentorship, Chicago business network"
  },
  {
    name: "Engineering Possibilities in College (EPIC)",
    organization: "Cal State Poly",
    type: "program",
    location: "San Luis Obispo, CA",
    duration: "Various",
    deadline: "Rolling",
    difficulty: "medium",
    eligibility: "High school students curious about engineering and technical problem-solving.",
    tags: ["engineering", "stem", "technology", "hands-on"],
    description: "A residential engineering camp at Cal Poly where students explore different engineering disciplines through projects and lab tours.",
    link: null,
    competitiveness: "Moderate",
    requirements: "Interest in engineering, ability to participate in residential program",
    upside: "Engineering exposure across disciplines, campus life, hands-on projects"
  },
  {
    name: "Maine Media Academy Summer Programs",
    organization: "Maine Media Academy",
    type: "program",
    location: "Rockport, ME",
    duration: "Various",
    deadline: "Rolling",
    difficulty: "medium",
    eligibility: "High school students interested in photography, filmmaking, writing, and visual arts.",
    tags: ["arts", "photography", "film", "creative"],
    description: "Week-long intensive workshops in photography, video production, creative writing, and graphic design at a professional arts campus.",
    link: null,
    competitiveness: "Moderate",
    requirements: "Passion for creative arts, specific program requirements vary",
    upside: "Professional equipment access, portfolio building, creative community"
  },
  {
    name: "Peace Ambassador Leadership Summit (PALS)",
    organization: "NVEEE",
    type: "program",
    location: "Various (In Person)",
    duration: "Various",
    deadline: "Rolling",
    difficulty: "easy",
    eligibility: "High school students passionate about social justice, equality, and community leadership.",
    tags: ["leadership", "social justice", "community", "activism"],
    description: "A leadership summit bringing together young people to develop skills in advocacy, community organizing, and peaceful change-making.",
    link: null,
    competitiveness: "Open enrollment",
    requirements: "Passion for social impact, willingness to collaborate",
    upside: "Activism skills, network of young leaders, social impact experience"
  },
  {
    name: "Students Making Illness a Little Easier (SMILE)",
    organization: "MarinHealth",
    type: "volunteer",
    location: "Kentfield, CA",
    duration: "Year Round (Jan 2026 - Dec 2027)",
    deadline: "Rolling",
    difficulty: "easy",
    eligibility: "Teen volunteers interested in healthcare, patient support, and community wellness.",
    tags: ["healthcare", "volunteer", "community", "service"],
    description: "A volunteer program where teens support hospital patients, assist families, and contribute to wellness programs at a regional medical center.",
    link: null,
    competitiveness: "Open enrollment",
    requirements: "Teen age, interest in healthcare, basic interpersonal skills",
    upside: "Healthcare exposure, patient interaction experience, community service hours"
  }
];
```
